import Head from "next/head";
import { useState } from "react";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export default function Home() {
  const handleSubmit = (e) => {
    e.preventDefault();
    toast.success("Message sent successfully", {
      position: "top-left",
      autoClose: 1000,
      hideProgressBar: true,
      closeOnClick: true,
      pauseOnHover: false,
      draggable: true,
      progress: undefined,
      theme: "light",
    });
    setName("");
    setEmail("");
    setSubject("");
    setMessage("");
  };
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [subject, setSubject] = useState("");
  const [message, setMessage] = useState("");

  const handleChange = (e) => {
    const { name, value } = e.target;
    if (name === "name") setName(value);
    else if (name === "email") setEmail(value);
    else if (name === "subject") setSubject(value);
    else if (name === "message") setMessage(value);
  };
  return (
    <>
      <Head>
        {/* <title>myHospital.com | Home</title> */}
        <title>HETSO | Home</title>
        <meta name="description" content="Generated by team H2SO4" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <div>
        <ToastContainer
          position="top-left"
          autoClose={5000}
          hideProgressBar={true}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <header
          className="jumbotron back-img"
          style={{
            backgroundImage: `url("img3.jpg")`,
            display: "flex",
            backgroundSize: "cover",
            backgroundPosition: "center",
            height: 85 + "vh",
            backgroundRepeat: "no-repeat",
            width: 100 + "%",
          }}
        >
          <div
            className="introinner"
            style={{ display: "block", marginTop: "142px", marginLeft: "40px" }}
          >
            <h1 className="text-uppercase text-danger font-bold">
              Welcome to HETSO
            </h1>
            <p className="font-italic font-bold" style={{ color: "black" }}>
              Customer's Heath is our aim
            </p>
            <a
              href="requester/RequesterLogin.php"
              className="btn btn-success mr-4 mx-15"
            >
              Login
            </a>
          </div>
        </header>
        <div
          className="container"
          style={{
            alignItems: "center",
            display: "flex",
            marginTop: 50 + "px",
          }}
        >
          <div
            className="ourservice"
            style={{
              width: 80 + "vw",
              alignItems: "center",
              backgroundColor: "rgb(192, 192, 181)",
            }}
          >
            <h3
              className="text-center"
              style={{ margin: 10 + "px" }}
              id="about"
            >
              WHY HETSO?
            </h3>
            <p style={{ margin: 5 + "px" }}>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ab
              assumenda non at eos ex quod sapiente, vero excepturi Ab assumenda
              non at eos ex quod sapiente, vero excepturi Ab assumenda non at
              eos ex quod sapiente, vero excepturi Ab assumenda non at eos ex
              quod sapiente, vero excepturi Ab assumenda non at eos ex quod
              sapiente, vero excepturi Ab assumenda non at eos ex quod sapiente,
              vero excepturi Ab assumenda non at eos ex quod sapiente, vero
              excepturi Ab assumenda non at eos ex quod sapiente, vero excepturi
              Ab assumenda non at eos ex quod sapiente, vero excepturi Ab
              assumenda non at eos ex quod sapiente, vero excepturi itaque nihil
              eaque, error corrupti dolor maiores repudiandae unde possimus,
              tenetur reprehenderit debitis. Eaque, delectus natus. Repudiandae
              minus consectetur deserunt rem, at modi voluptatibus culpa ducimus
              delectus ullam quae sed quibusdam dolorem atque voluptates
              exercitationem corrupti sit. Magnam voluptatem voluptas nihil
              nesciunt deleniti quo deserunt, a atque provident. Assumenda
              dignissimos, deserunt illum consectetur enim veritatis ut tempore
              maxime rem odio sunt cupiditate provident dicta perferendis atque
              facere beatae libero. Laborum, omnis, ad illo nulla ipsum cum
              vitae vel autem cumque voluptatem reiciendis?
            </p>
          </div>
        </div>
        <div className="container" id="Contact">
          <h2 className="text-center mb-4" style={{ margin: 60 + "px" }}>
            Contact Us
          </h2>
          <div className="row">
            <div className="col-md-8">
              <form action="" method="POST">
                <input
                  type="text"
                  className="form-control"
                  name="name"
                  placeholder="Name"
                  value={name}
                  onChange={handleChange}
                />
                <br />
                <input
                  type="text"
                  className="form-control"
                  name="subject"
                  placeholder="Subject"
                  onChange={handleChange}
                  value={subject}
                />
                <br />
                <input
                  type="email"
                  className="form-control"
                  name="email"
                  placeholder="Email"
                  onChange={handleChange}
                  value={email}
                />
                <br />
                <textarea
                  name="message"
                  id=""
                  cols="20"
                  rows="10"
                  className="form-control"
                  placeholder="How can we help you?"
                  onChange={handleChange}
                  value={message}
                ></textarea>
                <br />
                <button
                  className="btn btn-primary mx-[50%]"
                  onClick={handleSubmit}
                >
                  Send
                </button>
                <br />
                <br />
              </form>
            </div>
            <div className="col-md-4 text-center">
              <strong>Headquarter:</strong>
              <br />
              HETSO Pvt. Ltd. Ashoknagar, Lucknow <br />
              Uttar Pradesh - 123455 <br />
              Phone: 8978643542 <br />
              <a
                href="#"
                // target="_blank"
                style={{ color: "#dc3545", textDecoration: "none" }}
              >
                www.hetso.com
              </a>
              <br />
              <br />
              <br />
              <strong>Branch 1:</strong>
              <br />
              HETSO Pvt. Ltd. Rashiagar,Allahbad <br />
              Uttar Pradesh - 156755 <br />
              Phone: 897788692 <br />
              <a
                href="#"
                // target="_blank"
                style={{ color: "#dc3545", textDecoration: "none" }}
              >
                www.hetso.com
              </a>
              <br />
              <br />
              <br />
              <strong>Branch 2:</strong>
              <br />
              HETSO Pvt. Ltd. Ektanagar,Tapri <br />
              Uttar Pradesh - 178755 <br />
              Phone: 87894322 <br />
              <a
                href="#"
                // target="_blank"
                style={{ color: "#dc3545", textDecoration: "none" }}
              >
                www.hetso.com
              </a>
              <br />
              <br />
              <br />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
